# Generated by Django 4.1.1 on 2022-09-30 17:08

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200)),
                ('nome_arquivo', models.CharField(max_length=200)),
                ('arquivo', models.FileField(upload_to='')),
                ('data_criacao', models.DateTimeField(blank=True, default=datetime.datetime(2022, 9, 30, 14, 8, 7, 745798))),
            ],
        ),
    ]
